<?php
// ########## Data du formulaire : 
$villes = array ( 'Abbeville',
				'Agen',
				'Ajaccio',
				'Alençon',
				'Ambérieu',
				'Angers',
				'Auxerre',
				'Bastia',
				'Besançon',
				'Biarritz',
				'Bordeaux',
				'Bourg St Maurice',
				'Bourges',
				'Brest',
				'Caen',
				'Carcassonne',
				'Carpentras',
				'Chambéry',
				'Chartres',
				'Chateauroux',
				'Clermont Ferrand',
				'Colmar',
				'Dijon',
				'Embrun',
				'Evreux',
				'Grenoble',
				'Gourdon',
				'La Rochelle',
				 'Langres',
				'Le Mans',
				'Le Puy',
				'Lille',
				'Limoges',
				 'Luxeuil',
				'Lyon',
				'Mâcon',
				'Marseille',
				'Melun',
				'Metz',
				'Millau',
				'Montélimar',
				'Montpellier',
				'Mulhouse',
				'Nancy',
				'Nantes',
				'Nevers',
				'Nice',
				'Nimes',
				'Orléans',
				'Pau',
				'Paris le Bourget',
				'Perpignan',
				'Poitiers',
				'Reims',
				'Rennes',
				'Rouen',
				'St Etienne',
				'St Quentin',
				'Strasbourg',
				'Toulon',
				'Toulouse',
				'Tours',
				'Troyes',
				'Valence',
				'Vichy');

$inclinaisons = array ('horizontale',
						'5',
						'10',
						'15',
						'20',
						'25',
						'30',
						'35',
						'40',
						'45',
						'50',
						'55',
						'60',
						'65',
						'70',
						'75',
						'80',
						'85',
						'verticale');

$orientations = array ('-165',
						'-150',
						'-135',
						'-120',
						'-105',
						'Est',
						'-75',
						'-60',
						'-45',
						'-30',
						'-15',
						'Sud',
						'+15',
						'+30',
						'+45',
						'+60',
						'+75',
						'Ouest',
						'+105',
						'+120',
						'+135',
						'+150',
						'+165',
						'Nord');

$albedos = array ('0.0',
				'0.1',
				'0.2',
				'0.3',
				'0.4',
				'0.5',
				'0.6',
				'0.7',
				'0.8',
				'0.9',
				'1.0');

// ########## Fin des data du formulaire 
?>
